---
- name: Set Facts
  set_fact:
    container_name: 'privatebin'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}/data"

- name: Create the {{container_name}} container
  docker_container:
    name: privatebin
    image: ghcr.io/privatebin/nginx-fpm-alpine:latest@sha256:ca61eca662d0cbe786b5bb2b82dbe00bd450189d5feeb5a96ae5602029bc7718
    restart_policy: always
    recreate: true
    networks:
      - name: traefik
    volumes:
      - /mnt/nfs/docker/privatebin/data:/srv/data
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
    labels:
      traefik.enable=true
      traefik.http.routers.{{container_name}}.rule=Host(`{{container_name}}.{{traefik_domain}}`)
      traefik.http.routers.{{container_name}}.entrypoints=https
      traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare