---
- name: Set Facts
  set_fact:
    container_name: 'stirlingpdf'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"

    #- name: Download tessdata
    #git:
    #repo: https://github.com/tesseract-ocr/tessdata.git
    #dest: "/opt/tessdata"
    #clone: yes
    #update: yes

- name: Create the {{container_name}} container
  docker_container:
    name: stirlingpdf
    image: ghcr.io/stirling-tools/s-pdf:0.24.1
    restart_policy: always
    recreate: true
    networks:
      - name: traefik
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      DOCKER_ENABLE_SECURITY: "false"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "false"
    volumes:
      - /opt/tessdata:/usr/share/tessdata #Required for extra OCR languages
      - /mnt/nfs/docker/stirlingpdf/configs:/configs  
    labels:
      traefik.enable=true
      traefik.http.routers.{{container_name}}.rule=Host(`{{container_name}}.{{traefik_domain}}`)
      traefik.http.routers.{{container_name}}.entrypoints=https
      traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare
      
